### ISSUE TITLE
Optimize loading time

### ISSUE THREAD

**Issue by pierre** [killbill/slate#174]
It looks like we can easily break down the site in multiple pages, which would speed up the rendering time.

As an experiment, I created `source/account.html.md` with just the following:

```
---
includes:
  - account

title: Kill Bill

language_tabs:
   - shell
   - java
   - ruby
   - python

search: true
---
```

and removed the `account` include from the index:

```
diff --git a/source/index.html.md b/source/index.html.md
index c496418..7aeaace 100644
--- a/source/index.html.md
+++ b/source/index.html.md
@@ -2,7 +2,6 @@
 includes:
   - tenant
   - catalog
-  - account
   - payment-method
   - subscription
   - bundle
```

`middleman` (via the `deploy.sh` script) correctly created a `account.html` page with the right nav.

Besides breaking down the content in several pages, we'll also need to tweak the `layout.erb` to generate the correct sitenav.

Since this will break all bookmarks, I recommend doing this as part of the 0.24.x release.

**Comment by pierre** [comment]
As part of the 0.24.x release, since we're breaking urls, let's also deploy the docs at `https://apidocs.killbill.io` instead of https://killbill.github.io/slate/.

**Comment by KBbitsP** [comment]
Hi @pierre @reshmabidikar 

Started updating this. So I created a new account.html.md in the source directory. Now, the original _account.md has a link to bundle resource at this [point](https://killbill.github.io/slate/#account-bundle) and now we will be creating a new bundle page within the source directory. Am I right that this link will need to be updated to https://killbill.github.io/slate/bundle.html ?

![image](https://user-images.githubusercontent.com/75751774/232314161-ab5e7cba-7cb6-45e6-9bea-a0db67e93372.png)

**Comment by reshmabidikar** [comment]
> Now, the original _account.md has a link to bundle resource 

Did you remove `account` include from the index as mentioned [above](https://github.com/killbill/slate/issues/174#issue-1353381656)?

**Comment by KBbitsP** [comment]
Hi @reshmabidikar Yes for testing I tried it and then rolled back those changes. I just wanted to be sure about what the final link to new bundle ( after it is changed ) will look like. Once I clarify this, I can submit a test PR for account.md file.

**Comment by pierre** [comment]
This has been done and merged into the `new-branding` branch (see https://github.com/killbill/slate/pull/208).

**Comment by pierre** [comment]
Deployed!
