### ISSUE TITLE
New slate doc site - incorrect svg?

### ISSUE THREAD

**Issue by pierre** [killbill/slate#239]
Can you double check if the correct svg is checked-in?

<img width="406" alt="image" src="https://github.com/killbill/slate/assets/51940/8eb9dd81-bea6-4938-ac20-c010f3c83467">

**Comment by deekant** [comment]
@pierre we don't use it. Could be deleted

**Comment by pierre** [comment]
Fixed in d745f053c48c69b3daf2f9ccbc1fbebf1d510cce.
