### ISSUE TITLE
Documenting missed java endpoints.

### ISSUE THREAD

**Issue by wwjfrodriguez** [killbill/slate#60]
The following lists shows the missed java endpoints that I don't  found in the tests

For `Account Resource`. There 3 missed:

- [x] `POST /1.0/kb/accounts/{accountId}/block Block an account`
- [ ] `PUT /1.0/kb/accounts/{accountId}/cbaRebalancing Rebalance account CBA`
- [x] `POST /1.0/kb/accounts/payments Trigger a payment using the account external key (authorization, purchase or credit)`

 For `Bundle Resource`. There 3 missed:

- [x] `PUT /1.0/kb/bundles/{bundleId}/pause Pause a bundle`
- [x] `PUT /1.0/kb/bundles/{bundleId}/renameKey Update a bundle externalKey`
- [x] `PUT /1.0/kb/bundles/{bundleId}/resume Resume a bundle`

 For `Catalog Resource`. There 4 missed:

- [x] `GET /1.0/kb/catalog/phase Retrieve phase for a given subscription and date`
- [x] `GET /1.0/kb/catalog/plan Retrieve plan for a given subscription and date`
- [x] `GET /1.0/kb/catalog/priceList Retrieve priceList for a given subscription and date`
- [x] `GET /1.0/kb/catalog/product Retrieve product for a given subscription and date`

For `Invoice Resource`. There 9 missed:

- [x] `DELETE /1.0/kb/invoices/{invoiceId}/{invoiceItemId}/cba Delete a CBA item`
- [x] `POST /1.0/kb/invoices/catalogTranslation/{locale} Upload the catalog translation for the tenant`
- [x] `GET /1.0/kb/invoices/catalogTranslation/{locale} Retrieves the catalog translation for the tenant`
- [x] `POST /1.0/kb/invoices/manualPayTemplate Upload the manualPay invoice template for the tenant`
- [x] `GET /1.0/kb/invoices/manualPayTemplate/{locale} Retrieves the manualPay invoice template for the tenant`
- [x] `POST /1.0/kb/invoices/template Upload the invoice template for the tenant`
- [x] `GET /1.0/kb/invoices/template Retrieves the invoice template for the tenant`
- [x] `GET /1.0/kb/invoices/translation/{locale} Retrieves the invoice translation for the tenant`
- [x] `POST /1.0/kb/invoices/translation/{locale} Upload the invoice translation for the tenant`

 For `Payment Resource`. There 7 missed:
- [x] `POST /1.0/kb/payments/{paymentId}/chargebackReversals Record a chargeback reversal`
- [x] `POST /1.0/kb/payments/{paymentId}/chargebacks Record a chargeback`
- [x] `DELETE /1.0/kb/payments/{paymentTransactionId}/cancelScheduledPaymentTransaction Cancels a scheduled payment attempt retry`
- [x] `GET /1.0/kb/payments/attempts/{paymentAttemptId}/auditLogsWithHistory Retrieve payment attempt audit logs with history by id`
- [x] `POST /1.0/kb/payments/chargebackReversals Record a chargeback reversal`
- [x] `POST /1.0/kb/payments/chargebacks Record a chargeback`
- [x] `POST /1.0/kb/payments/refunds Refund an existing payment`

For `Subscription Resource`. There 1 missed:
- [x] `POST /1.0/kb/subscriptions/{subscriptionId}/block Block a subscription`

**Comment by reshmabidikar** [comment]
At first glance, looks like most of the endpoints here are already documented but worth going through again and confirming.
I've added checkboxes. @KBbitsP, as and when you review the ones in the sections assigned to you, could you please tick them? I'll do the same.

**Comment by KBbitsP** [comment]
For Accounts, this  one PUT /1.0/kb/accounts/{accountId}/cbaRebalancing Rebalance account CBA is missing completely ( JAVA/JS/PHP/Python/Ruby/Shell )

**Comment by reshmabidikar** [comment]
> For Payments, all the ones mentioned here are already documented.

Thanks for confirming @KBbitsP. I've ticked these.

**Comment by reshmabidikar** [comment]
> the ones mentioned for Bundle are also all documented

Thanks @KBbitsP, I've ticked these.

**Comment by KBbitsP** [comment]
Hi @reshmabidikar All the ones mentioned for Catalog are documented.

**Comment by KBbitsP** [comment]
Closing this. All these are documented!
